config/routes.rb
RailsBlog::Application.routes.draw do
  get "pages/info"
  resources :entries
  root to: redirect('/entries')

end

app/models/entry.rb
class Entry < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :picture %><br>
    <%= f.file_field :picture, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/entries/edit.html.erb
<h1>修改文章：<%= @entry.title %></h1>

<%= render 'form' %>

<%= link_to '顯示文章', @entry %> |
<%= link_to '回到列表', entries_path %>

app/views/entries/index.html.erb
<h1>文章列表</h1>

<% @entries.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |entry| %>
      <div class="col-md-4">
        <%= image_tag entry.picture_url, width: '100%' if entry.picture.present? %>
        <h4><%= link_to entry.title, entry %></h4>
        <%= entry.description %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="mod-article">

    <%= content_tag :section, class: 'title', style: (@entry.picture.present?) ? "background-image:url(#{@entry.picture_url});" : nil do %>
        <h1><%= @entry.title %></h1>
    <% end %>

    <div class="content">
      <%= @entry.description %>
    </div>

    <div class="actions pull-right">
      <%= link_to '編輯', edit_entry_path(@entry), class: 'btn btn-default' %>
      <%= link_to '刪除', @entry, data: { confirm: '你確定要刪除這篇文章嗎？' }, method: :delete, class: 'btn btn-danger' %>
      <%= link_to '回到列表', entries_path %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">啊嗚的部落格</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <%= content_tag :li, class: current_page?(entries_path) ? 'active' : '' do %>
                <%= link_to '文章列表', entries_path %>
            <% end %>
            <%= content_tag :li, class: current_page?(new_entry_path) ? 'active' : '' do %>
                <%= link_to '新增文章', new_entry_path %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        <%= yield %>
    </div>

    <footer>
      <div class="container">
        <hr>
        啊嗚出品，必屬佳作
      </div>
    </footer>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<h1>關於作者</h1>
<p>啊嗚就是我，我就是啊嗚！！！！</p>